### ISSUE TITLE
Refactor Driver

### ISSUE THREAD

**Issue by dancannon** [dancannon/gorethink#3]
Refactor https://github.com/christopherhesse/rethinkgo. If you have any ideas you want added please comment below and I will add it to the list.
## Tasks
- [x] Add base query tree structure
- [x] Develop better debug printing of the query tree
- [x] Add handling for basic data types
- [x] Add handling for arrays
- [x] Add handling for  objects
- [x] Add handling for functions
- [x] Add the Expr function (Important as it is used a lot internally)
- [x] Add ReQL functions ( #6 )
- [x] Add tests for all ReQL functions ( #7 )
- [x] Add code for handling requests and responses as well as encoding/decoding values to be sent/received ( #8 )
- [x] Add connection pooling ( #1 )
- [x] Add optional arguments functionality ( #4 )
- [x] Check for spelling errors/typos
- [x] Remove List and Obj
- [x] Add driver documentation + licence etc
## Notes
- There are currently some issues with scanning if the wrong type is passed. For example if the server returns a slice and the user scans in a map then the driver panics. It would be nice to catch this error
- It might be worth trying to have set types for each function with anonymous function as arguments such as map

**Comment by cespare** [comment]
re: Look into using channels for iterating through results.

I think this is generally an anti-pattern and a bad use of channels. Channels are lightweight, but not free. The usual iterator pattern does not use channels and just has a `Next`, `Value`/`Line`/`Row`/whatever, and `Err`. See, for instance, `bufio.Scanner` or `sql.Rows`.

**Comment by dancannon** [comment]
Yeah thanks after some more research I decided to go with a similar solution to bufio.Scanner.

**Comment by dancannon** [comment]
I believe the driver is now ready to be released. I will wait for the naming issue to be resolved and then tag 1.0.
